name: Python Package using Conda

on: [push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/my-env
            shell: bash
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/my-env
            shell: bash
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\my-env
            shell: cmd

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Install or Update dependencies
        run: |
          conda env update --file environment.yml --name base
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Activate Conda Env
        run: |
          conda activate base
          
      - name: Run tests
        shell: ${{ matrix.shell }}
        run: pytest ./tests
